import type { IntradayAlert } from "./intradayCompare.js";

// ── What we publish ─────────────────────────────────────────────────
// Public posts must stay GENERIC: no holdings, allocations, gaps, or buy
// sizing may leak. `SignalSource` is the explicit allowlist of fields that
// are safe to share. buildSignalLines() is the single chokepoint — it reads
// ONLY these fields, never `suggestedBuyValue`, `gapPct`, `currentPct`,
// `targetPct`, `suggestedBuyShares`, or `overlapDiscount`. A unit test
// asserts private values never appear in the output.
//
// This module is intentionally free of any config/network imports so it can
// be unit-tested without a config.json present (CI-safe). The credentialled
// posters live in src/social.ts.
export interface SignalSource {
  ticker: string;
  tickerFullName: string | null;
  action: string;
  confidence: number;
  reason: string;
  valueRating?: string;
  analysisUrl?: string;
}

export type SocialMode = "daily" | "intraday";
export type Platform = "x" | "facebook" | "linkedin" | "threads";

// ── Platform character budgets ──────────────────────────────────────
export const CHAR_BUDGET: Record<Platform, number> = {
  x: 280,
  threads: 500,
  linkedin: 3000,
  facebook: 60000,
};

export const DISCLAIMER = "Not financial advice. Auto-generated by Richfolio.";

// ── Helpers ─────────────────────────────────────────────────────────
function actionEmoji(action: string): string {
  switch (action) {
    case "STRONG BUY":
      return "🟢";
    case "BUY":
      return "🔵";
    default:
      return "⚪";
  }
}

const ACTION_RANK: Record<string, number> = { "STRONG BUY": 2, BUY: 1 };

function truncate(s: string, max: number): string {
  const clean = s.replace(/\s+/g, " ").trim();
  return clean.length <= max ? clean : clean.slice(0, max - 1).trimEnd() + "…";
}

// Sentence is private if it exposes the operator's holdings/sizing: a specific
// allocation gap, a dollar figure (comma-grouped, e.g. $7,119 — distinguishes
// portfolio amounts from per-share price levels like $205), an ETF overlap
// discount, an over/underweight call, or portfolio totals/position sizing.
// Generic framework mentions (e.g. "gap ≥ 5%") are NOT matched, so they survive.
const PRIVATE_SENTENCE =
  /(\$\s?\d{1,3}(?:,\d{3})+|allocation gap|overlap discount|after etf overlap|under-?weight|over-?weight|portfolio (?:value|total)|position siz)/i;
const COMMA_DOLLARS = /~?\$\s?\d{1,3}(?:,\d{3})+(?:\.\d+)?/g;

/**
 * Public posts must read cleanly and must NOT expose internal mechanics, the
 * portfolio-vs-watchlist distinction, or private portfolio data. The AI/guard
 * pipeline writes reasons for the operator-facing email + Telegram; we strip
 * those bits before they reach a public feed:
 *  - leading guard markers the pipeline prepends, e.g. "[Guard: ...] "
 *  - a leading "(Watch)" / "(Watching)" marker
 *  - any sentence mentioning the watch list (keeps framing uniform)
 *  - any sentence exposing allocation gaps, dollar sizing, or overlap discounts
 */
export function sanitizeReason(reason: string): string {
  let r = reason
    .replace(/\[Guard:[^\]]*\]/gi, "") // internal guard annotation
    .replace(/^\s*\((?:watch|watching)\)\s*/i, "") // leading watch marker
    .trim();
  r = r
    .split(/(?<=[.!?])\s+/)
    .filter((s) => !/watch\s?list/i.test(s) && !PRIVATE_SENTENCE.test(s))
    .join(" ")
    .trim();
  // Backstop: strip any comma-grouped dollar amount that survived in a kept
  // sentence, so a stray gap/value figure can never leak.
  r = r
    .replace(COMMA_DOLLARS, "")
    .replace(/\(\s*\)/g, "")
    .replace(/\s{2,}/g, " ")
    .trim();
  return r;
}

/**
 * Privacy chokepoint. Filters to publishable buy signals and projects each
 * onto the generic allowlist — nothing else from the source object survives.
 */
export function buildSignalLines(sources: SignalSource[]): SignalSource[] {
  return sources
    .filter((s) => s.action === "STRONG BUY" || s.action === "BUY")
    .map((s) => ({
      ticker: s.ticker,
      tickerFullName: s.tickerFullName ?? null,
      action: s.action,
      confidence: s.confidence,
      reason: sanitizeReason(s.reason),
      valueRating: s.valueRating,
      analysisUrl: s.analysisUrl,
    }))
    .sort(
      (a, b) =>
        (ACTION_RANK[b.action] ?? 0) - (ACTION_RANK[a.action] ?? 0) || b.confidence - a.confidence,
    );
}

/** Map intraday alerts to the generic signal shape (current action wins). */
export function intradayAlertsToSignals(alerts: IntradayAlert[]): SignalSource[] {
  return alerts.map((a) => ({
    ticker: a.ticker,
    tickerFullName: a.tickerFullName,
    action: a.currentAction,
    confidence: a.currentConfidence,
    reason: a.reason,
    valueRating: a.valueRating,
    analysisUrl: a.analysisUrl,
  }));
}

/**
 * Assemble the post text for one platform, packing as many signals as the
 * character budget allows. X stays terse (cashtag + confidence, no prose);
 * LinkedIn/Facebook include a truncated reason per signal.
 */
export function buildPostText(
  sources: SignalSource[],
  platform: Platform,
  mode: SocialMode,
  opts: { includeLinkInX?: boolean; hashtags?: string[] } = {},
): string {
  const lines = buildSignalLines(sources);
  if (lines.length === 0) return "";

  const budget = CHAR_BUDGET[platform];
  const header = mode === "daily" ? "📊 Today's signals" : "⚡ Signal update";
  const footer = `\n\n${DISCLAIMER}`;
  const verbose = platform !== "x";
  const includeLink = verbose || !!opts.includeLinkInX;

  // Hashtags only on the non-X platforms (FB / Threads / LinkedIn), where they
  // are clickable/searchable. X keeps inline $cashtags (native there) and its
  // 280-char budget can't spare a tag block. Ticker tags + configured generic
  // tags. Reserve an upper bound (all tickers) so packing stays within budget.
  const tag = (s: string) => `#${s.replace(/^#/, "").replace(/[^A-Za-z0-9]/g, "")}`;
  const generic = verbose ? (opts.hashtags ?? []).map(tag).filter((t) => t.length > 1) : [];
  const reserve = verbose
    ? `\n\n${[...lines.map((l) => tag(l.ticker)), ...generic].join(" ")}`.length
    : 0;

  const blocks: string[] = [];
  const usedTickers: string[] = [];
  let used = header.length + reserve + footer.length;

  for (const line of lines) {
    const head = `${actionEmoji(line.action)} ${line.action} $${line.ticker} (${line.confidence}%)${
      line.valueRating ? ` [${line.valueRating}]` : ""
    }`;
    const parts = [head];
    if (verbose) {
      const reason = truncate(line.reason, 280);
      if (reason) parts.push(reason);
      if (includeLink && line.analysisUrl) parts.push(line.analysisUrl);
    } else if (includeLink && line.analysisUrl) {
      parts.push(line.analysisUrl);
    }
    const block = parts.join("\n");
    // +2 for the blank-line separator between blocks
    if (used + block.length + 2 > budget) break;
    blocks.push(block);
    usedTickers.push(tag(line.ticker));
    used += block.length + 2;
  }

  // Nothing fit (e.g. X budget). Fall back to a bare cashtag line.
  if (blocks.length === 0) {
    const first = lines[0];
    blocks.push(
      `${actionEmoji(first.action)} ${first.action} $${first.ticker} (${first.confidence}%)`,
    );
  }

  // Build the actual hashtag line from the tickers that made it in (a subset of
  // what we reserved), so the final length never exceeds the budget.
  const tags = verbose ? [...usedTickers, ...generic] : [];
  const hashtagLine = tags.length ? `\n\n${tags.join(" ")}` : "";

  return `${header}\n\n${blocks.join("\n\n")}${hashtagLine}${footer}`;
}
