import type { IntradayAlert } from "./intradayCompare.js";

// ── What we publish ─────────────────────────────────────────────────
// Public posts must stay GENERIC: no holdings, allocations, gaps, or buy
// sizing may leak. `SignalSource` is the explicit allowlist of fields that
// are safe to share. buildSignalLines() is the single chokepoint — it reads
// ONLY these fields, never `suggestedBuyValue`, `gapPct`, `currentPct`,
// `targetPct`, `suggestedBuyShares`, or `overlapDiscount`. A unit test
// asserts private values never appear in the output.
//
// This module is intentionally free of any config/network imports so it can
// be unit-tested without a config.json present (CI-safe). The credentialled
// posters live in src/social.ts.
export interface SignalSource {
  ticker: string;
  tickerFullName: string | null;
  action: string;
  confidence: number;
  reason: string;
  valueRating?: string;
  analysisUrl?: string;
}

export type SocialMode = "daily" | "intraday";
export type Platform = "x" | "facebook" | "linkedin";

// ── Platform character budgets ──────────────────────────────────────
export const CHAR_BUDGET: Record<Platform, number> = {
  x: 280,
  linkedin: 3000,
  facebook: 60000,
};

export const DISCLAIMER = "Not financial advice. Auto-generated by Richfolio.";

// ── Helpers ─────────────────────────────────────────────────────────
function actionEmoji(action: string): string {
  switch (action) {
    case "STRONG BUY":
      return "🟢";
    case "BUY":
      return "🔵";
    default:
      return "⚪";
  }
}

const ACTION_RANK: Record<string, number> = { "STRONG BUY": 2, BUY: 1 };

function truncate(s: string, max: number): string {
  const clean = s.replace(/\s+/g, " ").trim();
  return clean.length <= max ? clean : clean.slice(0, max - 1).trimEnd() + "…";
}

/**
 * Privacy chokepoint. Filters to publishable buy signals and projects each
 * onto the generic allowlist — nothing else from the source object survives.
 */
export function buildSignalLines(sources: SignalSource[]): SignalSource[] {
  return sources
    .filter((s) => s.action === "STRONG BUY" || s.action === "BUY")
    .map((s) => ({
      ticker: s.ticker,
      tickerFullName: s.tickerFullName ?? null,
      action: s.action,
      confidence: s.confidence,
      reason: s.reason,
      valueRating: s.valueRating,
      analysisUrl: s.analysisUrl,
    }))
    .sort(
      (a, b) =>
        (ACTION_RANK[b.action] ?? 0) - (ACTION_RANK[a.action] ?? 0) || b.confidence - a.confidence,
    );
}

/** Map intraday alerts to the generic signal shape (current action wins). */
export function intradayAlertsToSignals(alerts: IntradayAlert[]): SignalSource[] {
  return alerts.map((a) => ({
    ticker: a.ticker,
    tickerFullName: a.tickerFullName,
    action: a.currentAction,
    confidence: a.currentConfidence,
    reason: a.reason,
    valueRating: a.valueRating,
    analysisUrl: a.analysisUrl,
  }));
}

/**
 * Assemble the post text for one platform, packing as many signals as the
 * character budget allows. X stays terse (cashtag + confidence, no prose);
 * LinkedIn/Facebook include a truncated reason per signal.
 */
export function buildPostText(
  sources: SignalSource[],
  platform: Platform,
  mode: SocialMode,
  opts: { includeLinkInX?: boolean } = {},
): string {
  const lines = buildSignalLines(sources);
  if (lines.length === 0) return "";

  const budget = CHAR_BUDGET[platform];
  const header = mode === "daily" ? "📊 Today's signals" : "⚡ Signal update";
  const footer = `\n\n${DISCLAIMER}`;
  const verbose = platform !== "x";
  const includeLink = verbose || !!opts.includeLinkInX;

  const blocks: string[] = [];
  let used = header.length + footer.length;

  for (const line of lines) {
    const head = `${actionEmoji(line.action)} ${line.action} $${line.ticker} (${line.confidence}%)${
      line.valueRating ? ` [${line.valueRating}]` : ""
    }`;
    const parts = [head];
    if (verbose) {
      const reason = truncate(line.reason, 280);
      if (reason) parts.push(reason);
      if (includeLink && line.analysisUrl) parts.push(line.analysisUrl);
    } else if (includeLink && line.analysisUrl) {
      parts.push(line.analysisUrl);
    }
    const block = parts.join("\n");
    // +2 for the blank-line separator between blocks
    if (used + block.length + 2 > budget) break;
    blocks.push(block);
    used += block.length + 2;
  }

  // Nothing fit (e.g. X budget). Fall back to a bare cashtag line.
  if (blocks.length === 0) {
    const first = lines[0];
    blocks.push(
      `${actionEmoji(first.action)} ${first.action} $${first.ticker} (${first.confidence}%)`,
    );
  }

  return `${header}\n\n${blocks.join("\n\n")}${footer}`;
}
